timestamp: '2025-05-24T09:52:34.628749+00:00'
best_model: GradientBoostingClassifier
best_model_params:
  n_estimators: 70
  learning_rate: 0.07097873346937768
  max_depth: 7
train_metrics:
  accuracy: 0.9763465374750642
  f1: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    wEsUM5s37z8=
  precision: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    2+rzr60+7z8=
  recall: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    omgV6Ysw7z8=
val_metrics:
  accuracy: 0.9606837606837607
  f1: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    SrPpxr+37j8=
  precision: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Tq0JB6hL7j8=
  recall: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    YvxLxOUm7z8=
optimization:
  enabled: true
  best_trial: 17
  cv_folds: 5
  direction: maximize
  mean_score: 0.9487000662464287
