version: '3.9'

services:
  app:
    image: "${ECR_IMAGE_URI}:latest"
    container_name: networksecurity_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    image: "${ECR_IMAGE_URI}:latest"
    container_name: networksecurity_worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "src.networksecurity.worker.celery_worker", "worker", "--loglevel=info"]

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
