
# Root folder where all timestamped artifacts will be saved
artifacts_root: artifacts

# MongoDB Configuration
mongodb:
  input_data_path: network_data/input_csv/phisingData.csv
  json_data_filename: input_data_json.json

# Data Ingestion Configuration
data_ingestion:
  ingested_data_filename: ingested_data.csv
  input_data_filename: input_data.csv

data_validation:
  root_dir:

data_transformation:
  root_dir:

model_trainer:
  root_dir:

model_evaluation:
  root_dir:

model_prediction:
  root_dir:
