# Root directory where all experiment artifacts will be stored
project:
  artifacts_root: artifacts

# MongoDB configuration block
mongo_handler:
  input_data_path: network_data/input_csv/phisingData.csv
  json_data_filename: input_data.json
  database_name: network_security_db
  collection_name: phishing_records

# Data ingestion configuration
data_ingestion:
  raw_data_filename: raw_data.csv
  ingested_data_filename: ingested_data.csv

# Data validation configuration
data_validation:
  validated_data_filename: validated_data.csv
  drift_report_filename: drift_report.yaml

# Data transformation configuration
data_transformation:
  transformed_train_filename: train.csv
  transformed_test_filename: test.csv
  preprocessing_object_filename: preprocessing.pkl

# Model trainer configuration
model_trainer:
  trained_model_filename: model.pkl

# Model evaluation configuration
model_evaluation:
  evaluation_report_filename: evaluation_report.yaml

# Prediction configuration
model_prediction:
  prediction_output_filename: prediction_output.csv
