# Root directory for all experiment artifacts
project:
  artifacts_root: artifacts

# MongoDB configuration
mongo_handler:
  input_data_path: network_data/input_csv/phisingData.csv
  json_data_filename: input_data.json
  database_name: network_security_db
  collection_name: phishing_records

# Data ingestion configuration
data_ingestion:
  raw_data_filename: raw_data.csv
  ingested_data_filename: ingested_data.csv

# Data validation configuration
data_validation:
  validated_data_filename: validated_data.csv
  drift_report_filename: drift_report.yaml

# Data transformation configuration
data_transformation:
  transformed_train_filename: train.npy
  transformed_test_filename: test.npy
  preprocessing_object_filename: preprocessing.pkl

# Model trainer configuration
model_trainer:
  trained_model_filename: model.pkl

# Model evaluation configuration
model_evaluation:
  evaluation_report_filename: evaluation_report.yaml

# Model prediction configuration
model_prediction:
  prediction_output_filename: prediction_output.csv

# Stable DVC-tracked data paths
data_paths:
  raw_data: data/raw/raw_data.csv
  processed_data: data/processed/cleaned_data.csv
  validated_data: data/validated/validated_data.csv
  transformed_train: data/transformed/train.npy
  transformed_test: data/transformed/test.npy
  preprocessor: data/transformed/preprocessing.pkl
  trained_model: data/model/model.pkl
  evaluation_report: data/evaluation/evaluation_report.yaml
  predictions: data/predictions/prediction_output.csv
