# Root directory for all experiment artifacts
project:
  artifacts_root: artifacts

# MongoDB configuration
mongo_handler:
  input_data_path: network_data/input_csv/phisingData.csv
  json_data_filename: input_data.json
  database_name: network_security_db
  collection_name: phishing_records

# Data ingestion configuration
data_ingestion:
  raw_data_filename: raw_data.csv
  ingested_data_filename: ingested_data.csv

# Data validation configuration
data_validation:
  validated_filename: validated_data.csv
  missing_report_filename: missing_values_report.json
  duplicates_report_filename: duplicates_report.yaml
  drift_report_filename: drift_report.yaml
  validation_report_filename: validation_report.yaml
  schema_hash_filename: schema_hash.json


# Data transformation configuration
data_transformation:
  transformed_train_data_filename: train_data.csv
  transformed_test_data_filename: test_data.csv
  validation_data_filename: validation_data.csv
  preprocessing_object_filename: preprocessing.pkl

# Model trainer configuration
model_trainer:
  trained_model_filename: model.pkl

# Model evaluation configuration
model_evaluation:
  evaluation_report_filename: evaluation_report.yaml

# Model prediction configuration
model_prediction:
  prediction_output_filename: prediction_output.csv

# Stable DVC-tracked data paths
data_paths:
  raw_data_dvc_filepath: data/raw/raw_data.csv
  validated_dvc_filepath: data/validated/validated_data.csv
  transformed_train_dvc_filepath: data/transformed/train.csv
  transformed_test_dvc_filepath: data/transformed/test.csv
  preprocessor_dvc_filepath: data/transformed/preprocessing.pkl
  trained_model_dvc_filepath: data/model/model.pkl
  predictions_dvc_filepath: data/predictions/prediction_output.csv
